package common;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class SwedbankSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    //System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(8000, TimeUnit.MILLISECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void swedbank() {
    // Test name: swedbank
    // Step # | name | target | value
    // 1 | open | /business/ | 
    driver.get("https://swedbank.ee/business/");
    // 2 | setWindowSize | 2576x1408 | 
    driver.manage().window().setSize(new Dimension(2576, 1408));
    
    if(driver.findElement(By.cssSelector(".ui-cookie-consent__accept-all-button")).isDisplayed()){
      driver.findElement(By.cssSelector(".ui-cookie-consent__accept-all-button")).click();
    }

    // 3 | click | css=#business\.cards > .ui-navitem__caption | 
    driver.findElement(By.cssSelector("#business\\.cards > .ui-navitem__caption")).click();
    // 4 | click | css=#business\.cards\.bankCards\.businessDebitCard > .ui-navitem__caption | 
    driver.findElement(By.cssSelector("#business\\.cards\\.bankCards\\.businessDebitCard > .ui-navitem__caption")).click();
    // 5 | verifyElementPresent | css=#Tab1-control > .ui-tabs__control | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#Tab1-control > .ui-tabs__control"));
      assert(elements.size() > 0);
    }
    // 6 | verifyElementPresent | css=#Tab2-control > .ui-tabs__control | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#Tab2-control > .ui-tabs__control"));
      assert(elements.size() > 0);
    }
    // 7 | verifyElementPresent | css=#Tab3-control > .ui-tabs__control | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#Tab3-control > .ui-tabs__control"));
      assert(elements.size() > 0);
    }
    // 8 | verifyElementPresent | css=#Tab4-control > .ui-tabs__control | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#Tab4-control > .ui-tabs__control"));
      assert(elements.size() > 0);
    }
    // 9 | verifyElementPresent | css=#Tab5-control > .ui-tabs__control | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#Tab5-control > .ui-tabs__control"));
      assert(elements.size() > 0);
    }
    // 10 | verifyText | css=h1 | Ärikliendi deebetkaart
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Ärikliendi deebetkaart"));
    // 11 | click | css=#Tab3-control > .ui-tabs__control | 
    driver.findElement(By.cssSelector("#Tab3-control > .ui-tabs__control")).click();
    // 12 | click | css=ui-curtains .ui-curtain__head svg | 
    driver.findElement(By.cssSelector("ui-curtains .ui-curtain__head svg")).click();
    // 13 | verifyText | css=ui-table:nth-child(2) tr:nth-child(3) > .col | 2,50 €
    assertThat(driver.findElement(By.cssSelector("ui-table:nth-child(2) tr:nth-child(3) > .col")).getText(), is("2,50 €"));
  }
}
